"""Protocol constants for llm-steganography v1."""

KEY_SIZE = 32
MIN_GROUP_COUNT = 2
MAX_GROUP_COUNT = 10
DEFAULT_GROUP_COUNT = 2
BLOCK_PAYLOAD_SIZE = 32
FRAME_SIZE = 33

RS_DATA_SIZE = FRAME_SIZE
RS_CODEWORD_SIZE = 48
RS_PARITY_SIZE = RS_CODEWORD_SIZE - RS_DATA_SIZE

CODE_BITS = RS_CODEWORD_SIZE * 8
RAW_BLOCK_BITS = BLOCK_PAYLOAD_SIZE * 8

CONTEXT_WIDTH = 3
DEFAULT_DELTA = float("inf")
DEFAULT_TEMPERATURE = 0.8
DEFAULT_TOP_P = 0.95
DEFAULT_TAIL_MAX_TOKENS = 64
DEFAULT_ROUNDTRIP_RETRIES = 3

MODEL_ID = "Qwen/Qwen3.5-4B"
MODEL_REVISION = "851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a"
TOKENIZER_FINGERPRINT = f"{MODEL_ID}@{MODEL_REVISION}"

START_CONTEXT = (
    0xFFFFFFFFFFFFFFF1,
    0xFFFFFFFFFFFFFFF2,
    0xFFFFFFFFFFFFFFF3,
)
